export const ADD_CART = 'ADD_CART'    //add cart
export const EMPTY_CART = 'EMPTY_CART'  //empty cart
export const BALL_IN_CART = 'BALL_IN_CART'  //ball get in cart
export const RECORD_ADDRESS = 'RECORD_ADDRESS'
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS'    //clear location info when locate again
export const FAIL_LOCATION = 'FAIL_LOCATION'  //fail location
export const RECORD_SUGGESTION = 'RECORD_SUGGESTION'
export const REDUCE_CART = 'REDUCE_CART'  //reduce shopping cart
export const RECORD_DELIVERY_ADDRESS = 'RECORD_DELIVERY_ADDRESS'  //delivery address
export const RECORD_RESTAURANT = 'RECORD_RESTAURANT'
export const UPDATE_CART = 'UPDATE_CART'  //update cart info when refresh page
export const LOCATION_READY = 'LOCATION_READY'  //get restaurant info of the location
export const DELETE_CART = 'DELETE_CART'    //delete item from cart
export const SAVE_PATH = 'SAVE_PATH'        //save path
export const RESET_PATH = 'RESET_PATH'     //reset path